import express from 'express';
import { getUser, getUsers, addUser, chanUser, delUser } from './UserControl.js';
import { validUser, check, validPhone } from './valid.js';
const router = express.Router();
router.put('/:id', validPhone, check, chanUser);
router.delete('/:id', delUser);
router.get('/:id', getUser);
router.post('/', validUser, check, addUser);
router.get('/', getUsers);
export default router;
